name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Python 3.9 einrichten
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        
    - name: Tests ausführen mit detaillierten Logs
      run: |
        echo "=== Starte Tests ==="
        pytest --cov=./ --cov-branch --cov-report=xml \
               --verbose \
               --tb=short \
               --no-header \
               --tb=line
      continue-on-error: true
      
    - name: Test-Zusammenfassung anzeigen
      if: always()
      run: |
        echo "=== TEST ABGESCHLOSSEN ==="
        echo "Details siehe oben in den pytest Logs"
        
    - name: Coverage zu Codecov hochladen
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true