name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Python 3.10 einrichten
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Tests ausführen
      run: |
        pytest